//! /etc/frr/frr.conf for this member — a pure generator, testable and diffable without a
//! live host: per-segment OSPF+BFD interface blocks, per-zone OSPF instances and identity
//! advertisement, VRRP on the storage primary, the ingress legs' iBGP sessions, and zebra
//! source-pinning so identities are the addresses on the wire.

use crate::derive::View;
use crate::error::Result;
use crate::model::MemberKind;

/// The ownership line `up` checks before overwriting /etc/frr/frr.conf: only a file that
/// carries it is provably cfab's to replace.
pub const OWNERSHIP_MARKER: &str = "! cfab-fabric (generated by cfab — do not hand-edit)";

pub fn generate(view: &View) -> Result<String> {
    let f = view.fabric;
    let n = view.node();
    let mut out = String::new();
    out.push_str(&format!(
        "frr defaults traditional\nhostname {}\n{OWNERSHIP_MARKER}\n\
         bfd\n profile cfab-fast\n  receive-interval {}\n  transmit-interval {}\n  \
         detect-multiplier {}\n exit\nexit\n",
        view.member.name, f.bfd_rx_ms, f.bfd_tx_ms, f.bfd_mult
    ));

    // Segment interface blocks. A leaf's transit links carry cost + LEAF_COST_OFFSET (never a
    // transit); the storage-primary block carries the VRRP lines on a VRRP host. Quirk kept
    // stable for config diffing: a storage-primary block WITHOUT VRRP (a leaf, or VRRP_GW=0)
    // keeps one blank line before `exit`.
    for r in view.class_rows() {
        let zone = f.zone(&r.zone)?;
        let mut extra = String::new();
        if r.zone == "storage" && r.role == crate::model::Role::Primary {
            if view.kind() == MemberKind::Host && f.vrrp_gw {
                let (vrid, prio) = (f.vrrp_vrid, view.vrrp_prio()?);
                extra = format!(
                    " vrrp {vrid} version 3\n vrrp {vrid} priority {prio}\n \
                     vrrp {vrid} advertisement-interval {}\n vrrp {vrid} ip {}\n",
                    f.vrrp_advert_ms,
                    view.vrrp_vip()?
                );
            } else {
                extra = "\n".to_string();
            }
        }
        let cost = if view.kind() == MemberKind::Leaf {
            r.ospf_cost + f.leaf_cost_offset
        } else {
            r.ospf_cost
        };
        out.push_str(&format!(
            "interface {}\n ip ospf {} area 0\n ip ospf network broadcast\n \
             ip ospf hello-interval {}\n ip ospf dead-interval {}\n ip ospf cost {}\n \
             ip ospf bfd\n ip ospf bfd profile cfab-fast\n{}exit\n",
            r.ifname, zone.id, f.ospf_hello, f.ospf_dead, cost, extra
        ));
    }

    // Identities, OSPF instances, per-zone prefix-lists, and each gw zone's return-path static
    // (the zone table's default = the zone's gw, resolved recursively over OSPF).
    for z in &f.zones {
        out.push_str(&format!(
            "interface cfab-id{}\n ip ospf {} area 0\n ip ospf passive\nexit\n\
             router ospf {}\n ospf router-id {}.0.{n}\nexit\n\
             ip prefix-list cfab{} seq 5 permit {}.0.0/16 le 32\n",
            z.id,
            z.id,
            z.id,
            z.block(),
            z.id,
            z.block()
        ));
        if let Some(gw) = &z.gw {
            out.push_str(&format!(
                "ip route 0.0.0.0/0 {} table {}\n",
                gw.router, z.id
            ));
        }
    }

    // Ingress legs: passive in the zone's instance (the router's /24 reaches the peers; no
    // adjacency — the router is not in the IGP).
    let gw_rows = view.gw_rows();
    for r in &gw_rows {
        let zone = f.zone(&r.zone)?;
        out.push_str(&format!(
            "interface {}\n ip ospf {} area 0\n ip ospf passive\nexit\n",
            r.ifname, zone.id
        ));
    }

    // One iBGP session per ingress leg (fabric.conf BGP_*), advertising only that zone's
    // identities; next-hop-self is load-bearing (a redistributed identity otherwise carries an
    // OSPF next hop the router cannot resolve after a segment loss — measured).
    if !gw_rows.is_empty() {
        let first = f.zone(&gw_rows[0].zone)?;
        out.push_str(&format!("router bgp {}\n", f.bgp_as));
        out.push_str(&format!(" bgp router-id {}.0.{n}\n", first.block()));
        for r in &gw_rows {
            let z = f.zone(&r.zone)?;
            let gw = z.gw.as_ref().expect("gw_rows only lists gw zones");
            out.push_str(&format!(
                " neighbor {} remote-as {}\n neighbor {} update-source {}\n \
                 neighbor {} timers {} {}\n neighbor {} timers connect {}\n",
                gw.router,
                f.bgp_as,
                gw.router,
                gw.leg_cidr(n)
                    .split_once('/')
                    .map(|(a, _)| a.to_string())
                    .unwrap_or_default(),
                gw.router,
                f.bgp_keepalive_s,
                f.bgp_hold_s,
                gw.router,
                f.bgp_connect_s
            ));
        }
        out.push_str(" address-family ipv4 unicast\n");
        for r in &gw_rows {
            let z = f.zone(&r.zone)?;
            let gw = z.gw.as_ref().expect("gw_rows only lists gw zones");
            out.push_str(&format!(
                "  network {}.0.{n}/32\n  redistribute ospf {}\n  neighbor {} next-hop-self\n  \
                 neighbor {} prefix-list cfab-id{} out\n  neighbor {} prefix-list cfab-none in\n",
                z.block(),
                z.id,
                gw.router,
                gw.router,
                z.id,
                gw.router
            ));
        }
        out.push_str(" exit-address-family\nexit\n");
        for r in &gw_rows {
            let z = f.zone(&r.zone)?;
            out.push_str(&format!(
                "ip prefix-list cfab-id{} seq 5 permit {}.0.0/24 ge 32\n",
                z.id,
                z.block()
            ));
        }
        out.push_str("ip prefix-list cfab-none seq 5 deny 0.0.0.0/0 le 32\n");
    }

    // zebra src-pinning: identities must be the addresses on the wire.
    let mut i = 10;
    for z in &f.zones {
        out.push_str(&format!(
            "route-map CFAB_SRC permit {i}\n match ip address prefix-list cfab{}\n \
             set src {}.0.{n}\nexit\n",
            z.id,
            z.block()
        ));
        i += 10;
    }
    out.push_str("route-map CFAB_SRC permit 100\nexit\nip protocol ospf route-map CFAB_SRC\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::RawConfig;
    use crate::model::Fabric;

    fn fabric() -> Fabric {
        let text =
            std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/examples/fabric.conf"))
                .unwrap();
        Fabric::from_raw(&RawConfig::parse(&text).unwrap()).unwrap()
    }

    #[test]
    fn host_has_bgp_and_vrrp() {
        let f = fabric();
        let v = View::new(&f, "pve1-tb").unwrap();
        let conf = generate(&v).unwrap();
        assert!(
            conf.contains(OWNERSHIP_MARKER),
            "up's ownership guard keys on this"
        );
        assert!(conf.contains("router bgp 65000"));
        assert!(conf.contains(" bgp router-id 10.249.0.1\n"));
        assert!(conf.contains(" neighbor 192.168.249.254 update-source 192.168.249.1\n"));
        assert!(conf.contains("  network 10.249.0.1/32\n"));
        assert!(conf.contains(" vrrp 99 priority 100\n"));
        assert!(conf.contains(" vrrp 99 ip 10.99.1.254\n"));
        assert!(conf.contains("ip route 0.0.0.0/0 192.168.249.254 table 249\n"));
        assert!(
            conf.contains("interface cfab-gw249\n ip ospf 249 area 0\n ip ospf passive\nexit\n")
        );
        assert!(conf.contains(" ip ospf cost 10\n"));
        assert!(conf.ends_with("ip protocol ospf route-map CFAB_SRC\n"));
    }

    #[test]
    fn leaf_offsets_costs_and_has_no_bgp_no_vrrp() {
        let f = fabric();
        let v = View::new(&f, "pve3-tb").unwrap();
        let conf = generate(&v).unwrap();
        assert!(!conf.contains("router bgp"));
        assert!(!conf.contains("vrrp"));
        assert!(conf.contains(" ip ospf cost 30010\n"));
        // The parity quirk: a storage-primary block without VRRP keeps the blank line.
        assert!(conf.contains(" ip ospf bfd profile cfab-fast\n\nexit\n"));
    }
}
